In [1]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
#1D Array
arr1=np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [ ]:
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [6]:
arr2=np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(arr2)

[[1 2 3 4 5]
 [6 7 8 9 0]]


In [8]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [10]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
a=np.array([[1,2,3],[4,5,6]])
print(a)
print(a.shape)
print(a.ndim) #Number of Dimension
print(a.size)
print(a.dtype)



[[1 2 3]
 [4 5 6]]
(2, 3)
2
6
int64


In [14]:
#Numpy Vectorized Operation
a1=np.array([1,2,3,4,5])
a2=np.array([10,20,30,40,50])
print(a1+a2)
print(a1-a2)
print(a1*a2)
print(a1/a2)

[11 22 33 44 55]
[ -9 -18 -27 -36 -45]
[ 10  40  90 160 250]
[0.1 0.1 0.1 0.1 0.1]


In [17]:
#Universal Function
a=np.array([1,2,3,4,5])
print(np.sqrt(a))
print(np.exp(a))
print(np.sin(a))
print(np.log(a))


[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [23]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
arr[2][3]

np.int64(12)

In [28]:
data=np.array([1,2,3,4,5])
mean=np.mean(data)
standard_deviation=np.std(data)
normalizes_data=(data-mean)/standard_deviation
print(normalizes_data)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
